### ISSUE TITLE
License

### ISSUE THREAD

**Issue by tf2manu994** [Peter92/MouseTrack#1]
It would be much appreciated if a license was added. I propose the GPLv3, but obviously the owner can choose one.

It would ensure that no one will be legally harmed if they use the software or wish to modify it :)

**Comment by tf2manu994** [comment]
Why re-open? The license is there now.

I suppose you could add 2 couple lines at the top of each file of code stating that you have copyright, but this is by no means needed

**Comment by Peter92** [comment]
Thanks, and sorry haha, just for a few details since I have no idea about legal stuff - is that meant to protect the users from the owner, or the owner from the users?

**Comment by tf2manu994** [comment]
Both.

This means people can use it without fear of being sued by you and protecting you from being sued by someone using it wrong and then claiming it's your fault.

**Comment by tf2manu994** [comment]
Also, just thought I'd mention, your website appears to be down. (The one listed on your GitHub - peterhuntvfx.co.uk)

**Comment by Peter92** [comment]
Alright thanks, I guess it'll help down the line if more people start using the script. Also cheers for noticing, was going to apply for a job today haha, I'll have to try it get it fixed first :P

**Comment by tf2manu994** [comment]
Yep.

Hope your job interview goes well! <3

 If you own your domain and know html, you can actually use GitHub.io as a free web host for static pages.
